- name: Rocky Post-Provisioning
  hosts: all                      
  become: yes                     
  tasks:                          

  - name: .ssh directory exists   
    file:                         
      path: "/home/{{ ansible_user }}/.ssh"  
      state: directory            
      mode: 0700                 
      owner: "{{ ansible_user }}" 
      group: "{{ ansible_user }}" 

  - name: authorized_keys exists  
    file:
      path: "/home/{{ ansible_user }}/.ssh/authorized_keys"  
      state: touch
      mode: 0644                  
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Add admin public key    
    blockinfile:                  
      dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"  
      block: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"     
      owner: "{{ ansible_user }}"  
      group: "{{ ansible_user }}"
      mode: 0644

  - name: wheel group             
    user:                         
      name: "{{ ansible_user }}"  
      groups: wheel
      append: yes                 

  - name: passwordless sudo for admin  
    copy:                         
      dest: /etc/sudoers.d/admin  
      content: "admin ALL=(ALL) NOPASSWD:ALL\n" 
      mode: 0440                  

  - name: hostname                
    hostname:
      name: "{{ hostname }}"      

  - name: add hostname to /etc/hosts  
    lineinfile:                   
      path: /etc/hosts            
      line: "127.0.1.1 {{ hostname }}" 

  - name: remove default NM connection
    file:
      path: "/etc/NetworkManager/system-connections/{{ device }}.nmconnection"
      state: absent               

  - name: create new NM connection  
    copy:                           
      dest: "/etc/NetworkManager/system-connections/{{ device }}.nmconnection"  
      mode: 0600                    
      owner: root
      group: root
      content: |                    
        [connection]
        id={{ device }}
        type=ethernet
        interface-name={{ device }}
        autoconnect=true

        [ipv4]
        method=manual
        addresses={{ lan_ip }}/24
        gateway={{ gateway }}
        dns={{ name_server }};{{ gateway }};

        [ipv6]
        method=disabled

  - name: reload NM connections
    shell: "nmcli connection reload && nmcli connection up {{ device }}"

  - name: Reboot to apply network changes
    shell: "sleep 5 && shutdown -r now"
    async: 1
    poll: 0
